namespace QuanLyGiaiBong
{
    partial class AddClub
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddClub));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.btnXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pbAnh = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTai = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtAddTinh = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.txtAddHLV = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAddMaSan = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAddTenDoi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pTitlebar = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnClose = new System.Windows.Forms.Button();
            this.btnMinimize = new System.Windows.Forms.Button();
            this.txtLogoLink = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pbAnh)).BeginInit();
            this.pTitlebar.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnXoa
            // 
            this.btnXoa.AllowAnimations = true;
            this.btnXoa.AllowMouseEffects = true;
            this.btnXoa.AllowToggling = false;
            this.btnXoa.AnimationSpeed = 200;
            this.btnXoa.AutoGenerateColors = false;
            this.btnXoa.AutoRoundBorders = false;
            this.btnXoa.AutoSizeLeftIcon = true;
            this.btnXoa.AutoSizeRightIcon = true;
            this.btnXoa.BackColor = System.Drawing.Color.Transparent;
            this.btnXoa.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoa.BackgroundImage")));
            this.btnXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.ButtonText = "Xóa";
            this.btnXoa.ButtonTextMarginLeft = 0;
            this.btnXoa.ColorContrastOnClick = 45;
            this.btnXoa.ColorContrastOnHover = 45;
            this.btnXoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnXoa.CustomizableEdges = borderEdges1;
            this.btnXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoa.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnXoa.ForeColor = System.Drawing.Color.White;
            this.btnXoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoa.IconMarginLeft = 11;
            this.btnXoa.IconPadding = 10;
            this.btnXoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoa.IconSize = 25;
            this.btnXoa.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.IdleBorderRadius = 1;
            this.btnXoa.IdleBorderThickness = 1;
            this.btnXoa.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.IdleIconLeftImage = null;
            this.btnXoa.IdleIconRightImage = null;
            this.btnXoa.IndicateFocus = false;
            this.btnXoa.Location = new System.Drawing.Point(692, 296);
            this.btnXoa.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnXoa.Name = "btnXoa";
            this.btnXoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.OnDisabledState.BorderRadius = 1;
            this.btnXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnDisabledState.BorderThickness = 1;
            this.btnXoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.OnDisabledState.IconLeftImage = null;
            this.btnXoa.OnDisabledState.IconRightImage = null;
            this.btnXoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.onHoverState.BorderRadius = 1;
            this.btnXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.onHoverState.BorderThickness = 1;
            this.btnXoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.onHoverState.IconLeftImage = null;
            this.btnXoa.onHoverState.IconRightImage = null;
            this.btnXoa.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.OnIdleState.BorderRadius = 1;
            this.btnXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnIdleState.BorderThickness = 1;
            this.btnXoa.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.OnIdleState.IconLeftImage = null;
            this.btnXoa.OnIdleState.IconRightImage = null;
            this.btnXoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.OnPressedState.BorderRadius = 1;
            this.btnXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnPressedState.BorderThickness = 1;
            this.btnXoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnXoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.OnPressedState.IconLeftImage = null;
            this.btnXoa.OnPressedState.IconRightImage = null;
            this.btnXoa.Size = new System.Drawing.Size(120, 40);
            this.btnXoa.TabIndex = 5;
            this.btnXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoa.TextMarginLeft = 0;
            this.btnXoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXoa.UseDefaultRadiusAndThickness = true;
            this.btnXoa.Click += new System.EventHandler(this.btnXoa_Click);
            // 
            // pbAnh
            // 
            this.pbAnh.AllowFocused = false;
            this.pbAnh.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbAnh.AutoSizeHeight = true;
            this.pbAnh.BorderRadius = 0;
            this.pbAnh.Image = ((System.Drawing.Image)(resources.GetObject("pbAnh.Image")));
            this.pbAnh.IsCircle = true;
            this.pbAnh.Location = new System.Drawing.Point(508, 85);
            this.pbAnh.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.pbAnh.Name = "pbAnh";
            this.pbAnh.Size = new System.Drawing.Size(143, 143);
            this.pbAnh.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbAnh.TabIndex = 8;
            this.pbAnh.TabStop = false;
            this.pbAnh.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // btnThem
            // 
            this.btnThem.AllowAnimations = true;
            this.btnThem.AllowMouseEffects = true;
            this.btnThem.AllowToggling = false;
            this.btnThem.AnimationSpeed = 200;
            this.btnThem.AutoGenerateColors = false;
            this.btnThem.AutoRoundBorders = false;
            this.btnThem.AutoSizeLeftIcon = true;
            this.btnThem.AutoSizeRightIcon = true;
            this.btnThem.BackColor = System.Drawing.Color.Transparent;
            this.btnThem.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThem.BackgroundImage")));
            this.btnThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.ButtonText = "Thêm";
            this.btnThem.ButtonTextMarginLeft = 0;
            this.btnThem.ColorContrastOnClick = 45;
            this.btnThem.ColorContrastOnHover = 45;
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnThem.CustomizableEdges = borderEdges2;
            this.btnThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThem.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnThem.ForeColor = System.Drawing.Color.White;
            this.btnThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThem.IconMarginLeft = 11;
            this.btnThem.IconPadding = 10;
            this.btnThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThem.IconSize = 25;
            this.btnThem.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.IdleBorderRadius = 1;
            this.btnThem.IdleBorderThickness = 1;
            this.btnThem.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.IdleIconLeftImage = null;
            this.btnThem.IdleIconRightImage = null;
            this.btnThem.IndicateFocus = false;
            this.btnThem.Location = new System.Drawing.Point(692, 188);
            this.btnThem.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnThem.Name = "btnThem";
            this.btnThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.OnDisabledState.BorderRadius = 1;
            this.btnThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnDisabledState.BorderThickness = 1;
            this.btnThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.OnDisabledState.IconLeftImage = null;
            this.btnThem.OnDisabledState.IconRightImage = null;
            this.btnThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.onHoverState.BorderRadius = 1;
            this.btnThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.onHoverState.BorderThickness = 1;
            this.btnThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThem.onHoverState.IconLeftImage = null;
            this.btnThem.onHoverState.IconRightImage = null;
            this.btnThem.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.OnIdleState.BorderRadius = 1;
            this.btnThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnIdleState.BorderThickness = 1;
            this.btnThem.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnIdleState.IconLeftImage = null;
            this.btnThem.OnIdleState.IconRightImage = null;
            this.btnThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.OnPressedState.BorderRadius = 1;
            this.btnThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnPressedState.BorderThickness = 1;
            this.btnThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnPressedState.IconLeftImage = null;
            this.btnThem.OnPressedState.IconRightImage = null;
            this.btnThem.Size = new System.Drawing.Size(120, 40);
            this.btnThem.TabIndex = 6;
            this.btnThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThem.TextMarginLeft = 0;
            this.btnThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThem.UseDefaultRadiusAndThickness = true;
            // 
            // btnTai
            // 
            this.btnTai.AllowAnimations = true;
            this.btnTai.AllowMouseEffects = true;
            this.btnTai.AllowToggling = false;
            this.btnTai.AnimationSpeed = 200;
            this.btnTai.AutoGenerateColors = false;
            this.btnTai.AutoRoundBorders = false;
            this.btnTai.AutoSizeLeftIcon = true;
            this.btnTai.AutoSizeRightIcon = true;
            this.btnTai.BackColor = System.Drawing.Color.Transparent;
            this.btnTai.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTai.BackgroundImage")));
            this.btnTai.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTai.ButtonText = "Tải Ảnh";
            this.btnTai.ButtonTextMarginLeft = 0;
            this.btnTai.ColorContrastOnClick = 45;
            this.btnTai.ColorContrastOnHover = 45;
            this.btnTai.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnTai.CustomizableEdges = borderEdges3;
            this.btnTai.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTai.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTai.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTai.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTai.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTai.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnTai.ForeColor = System.Drawing.Color.White;
            this.btnTai.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTai.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTai.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTai.IconMarginLeft = 11;
            this.btnTai.IconPadding = 10;
            this.btnTai.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTai.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTai.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTai.IconSize = 25;
            this.btnTai.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.IdleBorderRadius = 1;
            this.btnTai.IdleBorderThickness = 1;
            this.btnTai.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.IdleIconLeftImage = null;
            this.btnTai.IdleIconRightImage = null;
            this.btnTai.IndicateFocus = false;
            this.btnTai.Location = new System.Drawing.Point(692, 85);
            this.btnTai.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnTai.Name = "btnTai";
            this.btnTai.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTai.OnDisabledState.BorderRadius = 1;
            this.btnTai.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTai.OnDisabledState.BorderThickness = 1;
            this.btnTai.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTai.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTai.OnDisabledState.IconLeftImage = null;
            this.btnTai.OnDisabledState.IconRightImage = null;
            this.btnTai.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.onHoverState.BorderRadius = 1;
            this.btnTai.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTai.onHoverState.BorderThickness = 1;
            this.btnTai.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTai.onHoverState.IconLeftImage = null;
            this.btnTai.onHoverState.IconRightImage = null;
            this.btnTai.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.OnIdleState.BorderRadius = 1;
            this.btnTai.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTai.OnIdleState.BorderThickness = 1;
            this.btnTai.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTai.OnIdleState.IconLeftImage = null;
            this.btnTai.OnIdleState.IconRightImage = null;
            this.btnTai.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.OnPressedState.BorderRadius = 1;
            this.btnTai.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTai.OnPressedState.BorderThickness = 1;
            this.btnTai.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(148)))), ((int)(((byte)(23)))));
            this.btnTai.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTai.OnPressedState.IconLeftImage = null;
            this.btnTai.OnPressedState.IconRightImage = null;
            this.btnTai.Size = new System.Drawing.Size(120, 40);
            this.btnTai.TabIndex = 7;
            this.btnTai.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTai.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTai.TextMarginLeft = 0;
            this.btnTai.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTai.UseDefaultRadiusAndThickness = true;
            // 
            // txtAddTinh
            // 
            this.txtAddTinh.AcceptsReturn = false;
            this.txtAddTinh.AcceptsTab = false;
            this.txtAddTinh.AnimationSpeed = 200;
            this.txtAddTinh.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddTinh.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddTinh.BackColor = System.Drawing.Color.Transparent;
            this.txtAddTinh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddTinh.BackgroundImage")));
            this.txtAddTinh.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAddTinh.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddTinh.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAddTinh.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddTinh.BorderRadius = 1;
            this.txtAddTinh.BorderThickness = 1;
            this.txtAddTinh.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddTinh.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddTinh.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAddTinh.DefaultText = "";
            this.txtAddTinh.FillColor = System.Drawing.Color.White;
            this.txtAddTinh.HideSelection = true;
            this.txtAddTinh.IconLeft = null;
            this.txtAddTinh.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddTinh.IconPadding = 10;
            this.txtAddTinh.IconRight = null;
            this.txtAddTinh.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddTinh.Lines = new string[0];
            this.txtAddTinh.Location = new System.Drawing.Point(198, 303);
            this.txtAddTinh.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddTinh.MaxLength = 32767;
            this.txtAddTinh.MinimumSize = new System.Drawing.Size(0, 1);
            this.txtAddTinh.Modified = false;
            this.txtAddTinh.Multiline = false;
            this.txtAddTinh.Name = "txtAddTinh";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddTinh.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddTinh.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddTinh.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddTinh.OnIdleState = stateProperties4;
            this.txtAddTinh.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddTinh.PasswordChar = '\0';
            this.txtAddTinh.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddTinh.PlaceholderText = "Enter text";
            this.txtAddTinh.ReadOnly = false;
            this.txtAddTinh.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddTinh.SelectedText = "";
            this.txtAddTinh.SelectionLength = 0;
            this.txtAddTinh.SelectionStart = 0;
            this.txtAddTinh.ShortcutsEnabled = true;
            this.txtAddTinh.Size = new System.Drawing.Size(144, 33);
            this.txtAddTinh.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddTinh.TabIndex = 10;
            this.txtAddTinh.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddTinh.TextMarginBottom = 0;
            this.txtAddTinh.TextMarginLeft = 3;
            this.txtAddTinh.TextMarginTop = 0;
            this.txtAddTinh.TextPlaceholder = "Enter text";
            this.txtAddTinh.UseSystemPasswordChar = false;
            this.txtAddTinh.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(33, 303);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(63, 18);
            this.label1.TabIndex = 9;
            this.label1.Text = "Mã tỉnh";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(33, 85);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(76, 18);
            this.label5.TabIndex = 11;
            this.label5.Text = "Đội bóng";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(33, 160);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(63, 18);
            this.label7.TabIndex = 12;
            this.label7.Text = "Mã sân";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(33, 232);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(126, 18);
            this.label8.TabIndex = 13;
            this.label8.Text = "Huấn luyện viên";
            // 
            // txtAddHLV
            // 
            this.txtAddHLV.AcceptsReturn = false;
            this.txtAddHLV.AcceptsTab = false;
            this.txtAddHLV.AnimationSpeed = 200;
            this.txtAddHLV.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddHLV.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddHLV.BackColor = System.Drawing.Color.Transparent;
            this.txtAddHLV.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddHLV.BackgroundImage")));
            this.txtAddHLV.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAddHLV.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddHLV.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAddHLV.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddHLV.BorderRadius = 1;
            this.txtAddHLV.BorderThickness = 1;
            this.txtAddHLV.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddHLV.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddHLV.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAddHLV.DefaultText = "";
            this.txtAddHLV.FillColor = System.Drawing.Color.White;
            this.txtAddHLV.HideSelection = true;
            this.txtAddHLV.IconLeft = null;
            this.txtAddHLV.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddHLV.IconPadding = 10;
            this.txtAddHLV.IconRight = null;
            this.txtAddHLV.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddHLV.Lines = new string[0];
            this.txtAddHLV.Location = new System.Drawing.Point(198, 232);
            this.txtAddHLV.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddHLV.MaxLength = 32767;
            this.txtAddHLV.MinimumSize = new System.Drawing.Size(0, 1);
            this.txtAddHLV.Modified = false;
            this.txtAddHLV.Multiline = false;
            this.txtAddHLV.Name = "txtAddHLV";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddHLV.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddHLV.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddHLV.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddHLV.OnIdleState = stateProperties8;
            this.txtAddHLV.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddHLV.PasswordChar = '\0';
            this.txtAddHLV.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddHLV.PlaceholderText = "Enter text";
            this.txtAddHLV.ReadOnly = false;
            this.txtAddHLV.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddHLV.SelectedText = "";
            this.txtAddHLV.SelectionLength = 0;
            this.txtAddHLV.SelectionStart = 0;
            this.txtAddHLV.ShortcutsEnabled = true;
            this.txtAddHLV.Size = new System.Drawing.Size(144, 33);
            this.txtAddHLV.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddHLV.TabIndex = 14;
            this.txtAddHLV.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddHLV.TextMarginBottom = 0;
            this.txtAddHLV.TextMarginLeft = 3;
            this.txtAddHLV.TextMarginTop = 0;
            this.txtAddHLV.TextPlaceholder = "Enter text";
            this.txtAddHLV.UseSystemPasswordChar = false;
            this.txtAddHLV.WordWrap = true;
            // 
            // txtAddMaSan
            // 
            this.txtAddMaSan.AcceptsReturn = false;
            this.txtAddMaSan.AcceptsTab = false;
            this.txtAddMaSan.AnimationSpeed = 200;
            this.txtAddMaSan.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddMaSan.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddMaSan.BackColor = System.Drawing.Color.Transparent;
            this.txtAddMaSan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddMaSan.BackgroundImage")));
            this.txtAddMaSan.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAddMaSan.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddMaSan.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAddMaSan.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddMaSan.BorderRadius = 1;
            this.txtAddMaSan.BorderThickness = 1;
            this.txtAddMaSan.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddMaSan.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddMaSan.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAddMaSan.DefaultText = "";
            this.txtAddMaSan.FillColor = System.Drawing.Color.White;
            this.txtAddMaSan.HideSelection = true;
            this.txtAddMaSan.IconLeft = null;
            this.txtAddMaSan.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddMaSan.IconPadding = 10;
            this.txtAddMaSan.IconRight = null;
            this.txtAddMaSan.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddMaSan.Lines = new string[0];
            this.txtAddMaSan.Location = new System.Drawing.Point(198, 160);
            this.txtAddMaSan.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddMaSan.MaxLength = 32767;
            this.txtAddMaSan.MinimumSize = new System.Drawing.Size(0, 1);
            this.txtAddMaSan.Modified = false;
            this.txtAddMaSan.Multiline = false;
            this.txtAddMaSan.Name = "txtAddMaSan";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddMaSan.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddMaSan.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddMaSan.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddMaSan.OnIdleState = stateProperties12;
            this.txtAddMaSan.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddMaSan.PasswordChar = '\0';
            this.txtAddMaSan.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddMaSan.PlaceholderText = "Enter text";
            this.txtAddMaSan.ReadOnly = false;
            this.txtAddMaSan.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddMaSan.SelectedText = "";
            this.txtAddMaSan.SelectionLength = 0;
            this.txtAddMaSan.SelectionStart = 0;
            this.txtAddMaSan.ShortcutsEnabled = true;
            this.txtAddMaSan.Size = new System.Drawing.Size(144, 33);
            this.txtAddMaSan.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddMaSan.TabIndex = 15;
            this.txtAddMaSan.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddMaSan.TextMarginBottom = 0;
            this.txtAddMaSan.TextMarginLeft = 3;
            this.txtAddMaSan.TextMarginTop = 0;
            this.txtAddMaSan.TextPlaceholder = "Enter text";
            this.txtAddMaSan.UseSystemPasswordChar = false;
            this.txtAddMaSan.WordWrap = true;
            // 
            // txtAddTenDoi
            // 
            this.txtAddTenDoi.AcceptsReturn = false;
            this.txtAddTenDoi.AcceptsTab = false;
            this.txtAddTenDoi.AnimationSpeed = 200;
            this.txtAddTenDoi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddTenDoi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddTenDoi.BackColor = System.Drawing.Color.Transparent;
            this.txtAddTenDoi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddTenDoi.BackgroundImage")));
            this.txtAddTenDoi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAddTenDoi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddTenDoi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAddTenDoi.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddTenDoi.BorderRadius = 1;
            this.txtAddTenDoi.BorderThickness = 1;
            this.txtAddTenDoi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddTenDoi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddTenDoi.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtAddTenDoi.DefaultText = "";
            this.txtAddTenDoi.FillColor = System.Drawing.Color.White;
            this.txtAddTenDoi.HideSelection = true;
            this.txtAddTenDoi.IconLeft = null;
            this.txtAddTenDoi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddTenDoi.IconPadding = 10;
            this.txtAddTenDoi.IconRight = null;
            this.txtAddTenDoi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddTenDoi.Lines = new string[0];
            this.txtAddTenDoi.Location = new System.Drawing.Point(198, 85);
            this.txtAddTenDoi.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddTenDoi.MaxLength = 32767;
            this.txtAddTenDoi.MinimumSize = new System.Drawing.Size(0, 1);
            this.txtAddTenDoi.Modified = false;
            this.txtAddTenDoi.Multiline = false;
            this.txtAddTenDoi.Name = "txtAddTenDoi";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddTenDoi.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddTenDoi.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddTenDoi.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddTenDoi.OnIdleState = stateProperties16;
            this.txtAddTenDoi.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtAddTenDoi.PasswordChar = '\0';
            this.txtAddTenDoi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddTenDoi.PlaceholderText = "Enter text";
            this.txtAddTenDoi.ReadOnly = false;
            this.txtAddTenDoi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddTenDoi.SelectedText = "";
            this.txtAddTenDoi.SelectionLength = 0;
            this.txtAddTenDoi.SelectionStart = 0;
            this.txtAddTenDoi.ShortcutsEnabled = true;
            this.txtAddTenDoi.Size = new System.Drawing.Size(144, 33);
            this.txtAddTenDoi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAddTenDoi.TabIndex = 16;
            this.txtAddTenDoi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddTenDoi.TextMarginBottom = 0;
            this.txtAddTenDoi.TextMarginLeft = 3;
            this.txtAddTenDoi.TextMarginTop = 0;
            this.txtAddTenDoi.TextPlaceholder = "Enter text";
            this.txtAddTenDoi.UseSystemPasswordChar = false;
            this.txtAddTenDoi.WordWrap = true;
            // 
            // pTitlebar
            // 
            this.pTitlebar.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(48)))), ((int)(((byte)(98)))));
            this.pTitlebar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pTitlebar.BackgroundImage")));
            this.pTitlebar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pTitlebar.BorderColor = System.Drawing.Color.Transparent;
            this.pTitlebar.BorderRadius = 3;
            this.pTitlebar.BorderThickness = 1;
            this.pTitlebar.Controls.Add(this.btnClose);
            this.pTitlebar.Controls.Add(this.btnMinimize);
            this.pTitlebar.Dock = System.Windows.Forms.DockStyle.Top;
            this.pTitlebar.Location = new System.Drawing.Point(0, 0);
            this.pTitlebar.Margin = new System.Windows.Forms.Padding(4);
            this.pTitlebar.Name = "pTitlebar";
            this.pTitlebar.ShowBorders = true;
            this.pTitlebar.Size = new System.Drawing.Size(900, 60);
            this.pTitlebar.TabIndex = 36;
            this.pTitlebar.Click += new System.EventHandler(this.pTitlebar_Click);
            this.pTitlebar.MouseDown += new System.Windows.Forms.MouseEventHandler(this.pTitlebar_MouseDown);
            // 
            // btnClose
            // 
            this.btnClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnClose.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(48)))), ((int)(((byte)(98)))));
            this.btnClose.FlatAppearance.BorderSize = 0;
            this.btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnClose.Font = new System.Drawing.Font("Microsoft Sans Serif", 16.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClose.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnClose.Location = new System.Drawing.Point(868, 2);
            this.btnClose.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(32, 46);
            this.btnClose.TabIndex = 8;
            this.btnClose.Text = "O";
            this.btnClose.UseVisualStyleBackColor = false;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // btnMinimize
            // 
            this.btnMinimize.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnMinimize.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(48)))), ((int)(((byte)(98)))));
            this.btnMinimize.FlatAppearance.BorderSize = 0;
            this.btnMinimize.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMinimize.Font = new System.Drawing.Font("Microsoft Sans Serif", 16.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMinimize.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnMinimize.Location = new System.Drawing.Point(830, 2);
            this.btnMinimize.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnMinimize.Name = "btnMinimize";
            this.btnMinimize.Size = new System.Drawing.Size(32, 46);
            this.btnMinimize.TabIndex = 7;
            this.btnMinimize.Text = "O";
            this.btnMinimize.UseVisualStyleBackColor = false;
            this.btnMinimize.Click += new System.EventHandler(this.btnMinimize_Click);
            // 
            // txtLogoLink
            // 
            this.txtLogoLink.AcceptsReturn = false;
            this.txtLogoLink.AcceptsTab = false;
            this.txtLogoLink.AnimationSpeed = 200;
            this.txtLogoLink.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLogoLink.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLogoLink.BackColor = System.Drawing.Color.Transparent;
            this.txtLogoLink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLogoLink.BackgroundImage")));
            this.txtLogoLink.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtLogoLink.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLogoLink.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtLogoLink.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLogoLink.BorderRadius = 1;
            this.txtLogoLink.BorderThickness = 1;
            this.txtLogoLink.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLogoLink.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLogoLink.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtLogoLink.DefaultText = "";
            this.txtLogoLink.FillColor = System.Drawing.Color.White;
            this.txtLogoLink.HideSelection = true;
            this.txtLogoLink.IconLeft = null;
            this.txtLogoLink.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLogoLink.IconPadding = 10;
            this.txtLogoLink.IconRight = null;
            this.txtLogoLink.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLogoLink.Lines = new string[0];
            this.txtLogoLink.Location = new System.Drawing.Point(507, 252);
            this.txtLogoLink.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtLogoLink.MaxLength = 32767;
            this.txtLogoLink.MinimumSize = new System.Drawing.Size(0, 1);
            this.txtLogoLink.Modified = false;
            this.txtLogoLink.Multiline = false;
            this.txtLogoLink.Name = "txtLogoLink";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLogoLink.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLogoLink.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLogoLink.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLogoLink.OnIdleState = stateProperties20;
            this.txtLogoLink.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtLogoLink.PasswordChar = '\0';
            this.txtLogoLink.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLogoLink.PlaceholderText = "Enter text";
            this.txtLogoLink.ReadOnly = false;
            this.txtLogoLink.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLogoLink.SelectedText = "";
            this.txtLogoLink.SelectionLength = 0;
            this.txtLogoLink.SelectionStart = 0;
            this.txtLogoLink.ShortcutsEnabled = true;
            this.txtLogoLink.Size = new System.Drawing.Size(144, 33);
            this.txtLogoLink.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtLogoLink.TabIndex = 37;
            this.txtLogoLink.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLogoLink.TextMarginBottom = 0;
            this.txtLogoLink.TextMarginLeft = 3;
            this.txtLogoLink.TextMarginTop = 0;
            this.txtLogoLink.TextPlaceholder = "Enter text";
            this.txtLogoLink.UseSystemPasswordChar = false;
            this.txtLogoLink.WordWrap = true;
            // 
            // AddClub
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(900, 400);
            this.Controls.Add(this.txtLogoLink);
            this.Controls.Add(this.pTitlebar);
            this.Controls.Add(this.txtAddTenDoi);
            this.Controls.Add(this.txtAddMaSan);
            this.Controls.Add(this.txtAddHLV);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txtAddTinh);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pbAnh);
            this.Controls.Add(this.btnThem);
            this.Controls.Add(this.btnTai);
            this.Controls.Add(this.btnXoa);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AddClub";
            this.Text = "AddClub";
            ((System.ComponentModel.ISupportInitialize)(this.pbAnh)).EndInit();
            this.pTitlebar.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoa;
        private Bunifu.UI.WinForms.BunifuPictureBox pbAnh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTai;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddTinh;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddHLV;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddMaSan;
        private Bunifu.UI.WinForms.BunifuTextBox txtAddTenDoi;
        private Bunifu.UI.WinForms.BunifuPanel pTitlebar;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.Button btnMinimize;
        private Bunifu.UI.WinForms.BunifuTextBox txtLogoLink;
    }
}